# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 236079ac58e498151bdb10f0283c5cae4d59a8263cff5b3a9356dde844930dbbde5443a302a5fcdb927948786f5e0a29eb7a88f59596929a97501e2457599159

test:
  secret_key_base: 757aa8156ddca3ea197b34655e8f113b9ccbfa133fd822203b8915b5dc2f540aca4a64904635e3101c6dfafd0f3f5d6c19ac9b7178d09aafa028d48e0b2fc214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
